# Generated by Django 5.0.14 on 2026-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão sobre vendas', max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_colaborador',
            field=models.BooleanField(default=False, help_text='Indica se o usuário também é um colaborador (funcionário)', verbose_name='É Colaborador?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_atendente',
            field=models.BooleanField(default=False, help_text='Pode ser selecionado como atendente em vendas', verbose_name='É Atendente/Garçom?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_caixa',
            field=models.BooleanField(default=False, help_text='Pode abrir e fechar caixas', verbose_name='É Operador de Caixa?'),
        ),
    ]
