# Generated by Django 5.0.14 on 2026-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_customuser_comissao_percentual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="comissao_percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Percentual de comissão sobre vendas",
                max_digits=5,
                verbose_name="Comissão (%)",
            ),
        ),
    ]
