# Generated by Django 5.2.9 on 2026-01-15 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_ficha_tecnica'),
        ('stock', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('codigo_lote', models.CharField(db_index=True, help_text='Código fornecido pelo fabricante ou gerado internamente', max_length=50, verbose_name='Código do Lote')),
                ('data_fabricacao', models.DateField(blank=True, help_text='Data de fabricação do produto (opcional)', null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(db_index=True, help_text='Data de validade/vencimento do lote', verbose_name='Data de Validade')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Saldo atual deste lote específico (atualizado automaticamente)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Saldo Atual')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre o lote (opcional)', verbose_name='Observação')),
                ('deposito', models.ForeignKey(help_text='Depósito onde o lote está armazenado', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='stock.deposito', verbose_name='Depósito')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(help_text='Produto deste lote', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='catalog.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['data_validade', 'data_fabricacao'],
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote específico desta movimentação (opcional, para controle FIFO/FEFO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='stock.lote', verbose_name='Lote'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['empresa', 'produto', 'deposito', 'data_validade'], name='stock_lote_empresa_796eda_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['empresa', 'data_validade'], name='stock_lote_empresa_e99c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['codigo_lote'], name='stock_lote_codigo__e1833b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('empresa', 'produto', 'deposito', 'codigo_lote')},
        ),
    ]
