# Generated by Django 5.2.9 on 2025-12-29 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_stock_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceipt',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockreceiptitem',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
