# Generated by Django 5.2.9 on 2025-12-29 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_customer'),
        ('estoque', '0004_add_fornecedor_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.address')),
            ],
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.deposito'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.deposito'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='motivo_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.motivoajuste'),
        ),
    ]
