# Generated by Django 5.2.9 on 2025-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_motivoajuste_deposito_stockmovement_deposito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='estornado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
