# Generated by Django 5.2.9 on 2025-12-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_purchaseorder_status'),
        ('estoque', '0006_stockreceipt_estornado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos', to='compras.purchaseorder'),
        ),
    ]
