# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome do depósito/armazém', max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=120, verbose_name='Slug')),
                ('codigo', models.CharField(blank=True, help_text='Código interno do depósito (opcional)', max_length=20, verbose_name='Código')),
                ('is_padrao', models.BooleanField(db_index=True, default=False, help_text='Usar como padrão em operações automáticas', verbose_name='Depósito Padrão')),
                ('is_virtual', models.BooleanField(default=False, help_text='Depósito virtual (não físico) usado para reservas', verbose_name='Virtual')),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou observações sobre o depósito', verbose_name='Descrição')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-is_padrao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('BALANCO', 'Balanço'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste')], db_index=True, help_text='Tipo de movimentação', max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade movimentada (sempre positivo - tipo define direção)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo unitário no momento da movimentação (snapshot)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Unitário')),
                ('documento', models.CharField(blank=True, help_text='Número da nota fiscal, pedido, etc. (opcional)', max_length=50, verbose_name='Documento')),
                ('observacao', models.TextField(blank=True, help_text='Detalhes ou motivo da movimentação (opcional)', verbose_name='Observação')),
                ('usuario', models.CharField(blank=True, help_text='Usuário responsável pela movimentação', max_length=150, verbose_name='Usuário')),
                ('deposito', models.ForeignKey(help_text='Depósito de origem (para saída) ou destino (para entrada)', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='stock.deposito', verbose_name='Depósito')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='catalog.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantidade atual em estoque (atualizado automaticamente)', max_digits=15, verbose_name='Quantidade')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='stock.deposito', verbose_name='Depósito')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='catalog.produto', verbose_name='Produto')),
                ('ultima_movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.movimentacao', verbose_name='Última Movimentação')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
                'ordering': ['produto__nome', 'deposito__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='deposito',
            index=models.Index(fields=['empresa', 'is_padrao'], name='stock_depos_empresa_1559cb_idx'),
        ),
        migrations.AddIndex(
            model_name='deposito',
            index=models.Index(fields=['codigo'], name='stock_depos_codigo_aeabd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deposito',
            unique_together={('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empresa', 'produto', 'deposito'], name='stock_movim_empresa_05b2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empresa', 'tipo'], name='stock_movim_empresa_d28fba_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['created_at'], name='stock_movim_created_ab151d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['documento'], name='stock_movim_documen_6287d7_idx'),
        ),
        migrations.AddIndex(
            model_name='saldo',
            index=models.Index(fields=['empresa', 'produto'], name='stock_saldo_empresa_0a5efc_idx'),
        ),
        migrations.AddIndex(
            model_name='saldo',
            index=models.Index(fields=['empresa', 'deposito'], name='stock_saldo_empresa_99b471_idx'),
        ),
        migrations.AddIndex(
            model_name='saldo',
            index=models.Index(fields=['quantidade'], name='stock_saldo_quantid_5e5e66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saldo',
            unique_together={('empresa', 'produto', 'deposito')},
        ),
    ]
