# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=120, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da categoria (opcional)', verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor valor aparece primeiro)', verbose_name='Ordem')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('parent', models.ForeignKey(blank=True, help_text='Categoria superior na hierarquia (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalog.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoComplemento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome do grupo (ex: "Escolha o Ponto", "Adicionais")', max_length=100, verbose_name='Nome')),
                ('obrigatorio', models.BooleanField(default=False, help_text='Cliente deve escolher ao menos uma opção deste grupo', verbose_name='Obrigatório')),
                ('min_qtd', models.PositiveIntegerField(default=0, help_text='Mínimo de opções que devem ser selecionadas', verbose_name='Quantidade Mínima')),
                ('max_qtd', models.PositiveIntegerField(default=1, help_text='Máximo de opções que podem ser selecionadas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade Máxima')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Grupo de Complemento',
                'verbose_name_plural': 'Grupos de Complementos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome do complemento (ex: "Mal Passado", "Bacon")', max_length=100, verbose_name='Nome')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor extra somado ao preço do produto principal', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Adicional')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('grupo', models.ForeignKey(help_text='Grupo ao qual este complemento pertence', on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='catalog.grupocomplemento', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Complemento',
                'verbose_name_plural': 'Complementos',
                'ordering': ['grupo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome comercial do produto', max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=220, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit - código interno do produto', max_length=50, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, help_text='EAN, UPC ou qualquer código de barras', max_length=50, verbose_name='Código de Barras')),
                ('tipo', models.CharField(choices=[('FISICO', 'Físico'), ('SERVICO', 'Serviço'), ('DIGITAL', 'Digital')], default='FISICO', help_text='Tipo do produto (Físico, Serviço ou Digital)', max_length=20, verbose_name='Tipo')),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Preço de venda padrão (pode variar por lista de preço)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Venda')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo médio de aquisição (referência)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Custo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto (opcional)', verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, help_text='Resumo para listagens (opcional)', max_length=250, verbose_name='Descrição Curta')),
                ('permite_venda_sem_estoque', models.BooleanField(default=False, help_text='Se True, permite vender mesmo com estoque zerado', verbose_name='Permite Venda sem Estoque')),
                ('destaque', models.BooleanField(db_index=True, default=False, help_text='Marcar para destacar em vitrines e promoções', verbose_name='Produto em Destaque')),
                ('imprimir_producao', models.BooleanField(default=True, help_text='Se True, item aparecerá na impressão da cozinha/bar', verbose_name='Imprimir na Produção')),
                ('categoria', models.ForeignKey(help_text='Categoria do produto', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
