# Generated by Django 5.2.9 on 2026-01-15 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('FINAL', 'Produto Final (Revenda)'), ('INSUMO', 'Insumo (Matéria Prima)'), ('COMPOSTO', 'Produto Composto (Receita)')], default='FINAL', help_text='FINAL=Revenda, INSUMO=Matéria-prima, COMPOSTO=Receita', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='FichaTecnicaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('quantidade_liquida', models.DecimalField(decimal_places=4, help_text='Quantidade do componente (ex: 0.150 = 150g, 1.000 = 1 unidade)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('custo_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para calcular automaticamente baseado no custo do componente', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Fixo')),
                ('observacao', models.CharField(blank=True, help_text='Observações sobre este componente (ex: "Picado", "Grelhado")', max_length=200, verbose_name='Observação')),
                ('componente', models.ForeignKey(help_text='Produto que compõe o produto pai', on_delete=django.db.models.deletion.PROTECT, related_name='usado_em', to='catalog.produto', verbose_name='Componente/Insumo')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto_pai', models.ForeignKey(help_text='Produto que possui esta ficha técnica', limit_choices_to={'tipo': 'COMPOSTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='catalog.produto', verbose_name='Produto Composto')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'ordering': ['componente__nome'],
                'indexes': [models.Index(fields=['empresa', 'produto_pai'], name='catalog_fic_empresa_8dbf49_idx'), models.Index(fields=['empresa', 'componente'], name='catalog_fic_empresa_e2f473_idx')],
                'unique_together': {('produto_pai', 'componente')},
            },
        ),
    ]
