# Generated by Django 5.2.9 on 2026-01-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_ficha_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do produto para o catálogo/cardápio', null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
    ]
