# Generated by Django 5.2.9 on 2026-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, help_text='Código Especificador da Substituição Tributária', max_length=7, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop_padrao',
            field=models.CharField(blank=True, help_text='Código Fiscal de Operações e Prestações (ex: 5102)', max_length=4, verbose_name='CFOP Padrão'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul', max_length=8, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(default='0', help_text='0=Nacional, 1=Estrangeira, etc.', max_length=1, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_comercial',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('FD', 'Fardo')], default='UN', help_text='Unidade de medida para NFe', max_length=10, verbose_name='Unidade Comercial'),
        ),
    ]
