# Generated by Django 5.2.9 on 2026-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_produto_cest_produto_cfop_padrao_produto_ncm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cest',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cfop_padrao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_comercial',
        ),
    ]
