# Generated by Django 5.0.14 on 2026-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_produto_cest_remove_produto_cfop_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, help_text='Código Especificador da Substituição Tributária', max_length=7, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop_padrao',
            field=models.CharField(default='5102', help_text='Código Fiscal de Operações e Prestações (Saída dentro do estado)', max_length=4, verbose_name='CFOP Padrão'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul (8 dígitos)', max_length=8, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem_mercadoria',
            field=models.CharField(default='0', help_text='0=Nacional, 1=Importada, etc.', max_length=1, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_comercial',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('M', 'Metro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('L', 'Litro'), ('CX', 'Caixa'), ('FD', 'Fardo'), ('DZ', 'Dúzia'), ('PR', 'Par')], default='UN', help_text='Unidade de medida para venda na nota fiscal', max_length=10, verbose_name='Unidade Comercial'),
        ),
    ]
