# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='FISICA', help_text='Pessoa Física ou Jurídica', max_length=10, verbose_name='Tipo de Pessoa')),
                ('nome', models.CharField(help_text='Nome completo (PF) ou Razão Social (PJ)', max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=220, verbose_name='Slug')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome comercial (apenas PJ)', max_length=200, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(db_index=True, help_text='CPF (11 dígitos) ou CNPJ (14 dígitos)', max_length=18, verbose_name='CPF/CNPJ')),
                ('rg_ie', models.CharField(blank=True, help_text='RG (PF) ou Inscrição Estadual (PJ)', max_length=20, verbose_name='RG/IE')),
                ('email', models.EmailField(blank=True, help_text='Email principal', max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, help_text='Telefone principal', max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, help_text='Celular/WhatsApp', max_length=20, verbose_name='Celular')),
                ('observacoes', models.TextField(blank=True, help_text='Notas ou comentários sobre o cliente', verbose_name='Observações')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['empresa', 'tipo_pessoa'], name='partners_cl_empresa_4330a6_idx'), models.Index(fields=['cpf_cnpj'], name='partners_cl_cpf_cnp_7733e3_idx'), models.Index(fields=['nome'], name='partners_cl_nome_17d64c_idx'), models.Index(fields=['slug'], name='partners_cl_slug_16b6f4_idx')],
                'unique_together': {('empresa', 'cpf_cnpj'), ('empresa', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='JURIDICA', help_text='Pessoa Física ou Jurídica', max_length=10, verbose_name='Tipo de Pessoa')),
                ('razao_social', models.CharField(help_text='Razão social do fornecedor', max_length=200, verbose_name='Razão Social')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=220, verbose_name='Slug')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome comercial', max_length=200, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(db_index=True, help_text='CPF ou CNPJ do fornecedor', max_length=18, verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, help_text='IE do fornecedor', max_length=20, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(blank=True, help_text='Email principal', max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, help_text='Telefone principal', max_length=20, verbose_name='Telefone')),
                ('contato_nome', models.CharField(blank=True, help_text='Pessoa de contato principal', max_length=100, verbose_name='Nome do Contato')),
                ('prazo_entrega_dias', models.PositiveIntegerField(default=0, help_text='Prazo médio de entrega em dias', verbose_name='Prazo de Entrega (dias)')),
                ('condicao_pagamento', models.CharField(blank=True, help_text='Condições de pagamento (ex: 30/60/90 dias)', max_length=100, verbose_name='Condição de Pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre o fornecedor', verbose_name='Observações')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['empresa', 'tipo_pessoa'], name='partners_fo_empresa_3b30a5_idx'), models.Index(fields=['cpf_cnpj'], name='partners_fo_cpf_cnp_97c0d4_idx'), models.Index(fields=['razao_social'], name='partners_fo_razao_s_14b66a_idx'), models.Index(fields=['slug'], name='partners_fo_slug_75555c_idx')],
                'unique_together': {('empresa', 'cpf_cnpj'), ('empresa', 'slug')},
            },
        ),
    ]
