# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('descricao', models.CharField(help_text='Descrição da conta a pagar', max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, help_text='Categoria da despesa (ex: Fornecedores, Aluguel, Salários)', max_length=50, verbose_name='Categoria')),
                ('valor_original', models.DecimalField(decimal_places=2, help_text='Valor original da conta', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Original')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de juros aplicados', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de multa aplicada', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto obtido', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque')], max_length=20, null=True, verbose_name='Tipo de Pagamento')),
                ('numero_documento', models.CharField(blank=True, help_text='Número da nota fiscal, recibo, etc.', max_length=50, verbose_name='Número do Documento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Fornecedor a ser pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='partners.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='financial_c_empresa_5d5a00_idx'), models.Index(fields=['empresa', 'data_vencimento'], name='financial_c_empresa_37dfae_idx'), models.Index(fields=['fornecedor', 'status'], name='financial_c_fornece_cddffb_idx'), models.Index(fields=['categoria'], name='financial_c_categor_4a7836_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('descricao', models.CharField(help_text='Descrição da conta a receber', max_length=200, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, help_text='Valor original da conta', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Original')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de juros aplicados', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de multa aplicada', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto concedido', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, help_text='Data de emissão da conta', verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(db_index=True, help_text='Data de vencimento da conta', verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data em que foi paga (null se não paga)', null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], db_index=True, default='PENDENTE', help_text='Status atual da conta', max_length=20, verbose_name='Status')),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque')], help_text='Forma de pagamento utilizada', max_length=20, null=True, verbose_name='Tipo de Pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre a conta', verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente responsável pelo pagamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='partners.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('venda', models.ForeignKey(blank=True, help_text='Venda que originou esta conta (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='sales.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='financial_c_empresa_e186cc_idx'), models.Index(fields=['empresa', 'data_vencimento'], name='financial_c_empresa_5ca662_idx'), models.Index(fields=['cliente', 'status'], name='financial_c_cliente_dfeee0_idx'), models.Index(fields=['venda'], name='financial_c_venda_i_b1e1bb_idx')],
            },
        ),
    ]
