# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import tenant.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(help_text='Nome comercial da empresa', max_length=200, verbose_name='Nome Fantasia')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=220, unique=True, verbose_name='Slug')),
                ('razao_social', models.CharField(help_text='Razão social completa da empresa', max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Cadastro Nacional de Pessoa Jurídica', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00 ou 00000000000000', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$|^\\d{14}$'), tenant.models.validar_cnpj], verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, help_text='Email principal da empresa', max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, help_text='Telefone principal', max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, help_text='Site da empresa (opcional)', verbose_name='Website')),
                ('logo', models.ImageField(blank=True, help_text='Logotipo da empresa', null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#3B82F6', help_text='Cor principal do tema (hex: #RRGGBB)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#10B981', help_text='Cor secundária do tema (hex: #RRGGBB)', max_length=7, verbose_name='Cor Secundária')),
                ('moeda', models.CharField(default='BRL', help_text='Código ISO da moeda (BRL, USD, EUR)', max_length=3, verbose_name='Moeda')),
                ('fuso_horario', models.CharField(default='America/Sao_Paulo', help_text='Fuso horário da empresa (ex: America/Sao_Paulo)', max_length=50, verbose_name='Fuso Horário')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se a empresa está ativa no sistema', verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
