# Generated by Django 5.2.9 on 2026-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ambiente_nfe',
            field=models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', help_text='Ambiente de envio (Produção ou Homologação)', max_length=1, verbose_name='Ambiente NFe'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_digital',
            field=models.FileField(blank=True, help_text='Arquivo .pfx ou .p12', null=True, upload_to='empresas/certificados/', verbose_name='Certificado Digital'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, help_text='Código IBGE do município (obrigatório para NFe)', max_length=7, verbose_name='Código IBGE'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc',
            field=models.CharField(blank=True, help_text='Código de Segurança do Contribuinte (NFCe)', max_length=100, verbose_name='CSC (Token)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_id',
            field=models.CharField(blank=True, help_text='Identificador do CSC (ex: 000001)', max_length=10, verbose_name='ID do CSC'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='IE da empresa', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='IM da empresa (opcional)', max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_nfe_atual',
            field=models.IntegerField(default=0, help_text='Último número de nota emitido', verbose_name='Número NFe Atual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - Excesso de Sublimite'), ('3', 'Regime Normal')], default='1', help_text='Regime de tributação para NFe', max_length=1, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='senha_certificado',
            field=models.CharField(blank=True, help_text='Senha para descriptografar o certificado', max_length=255, verbose_name='Senha do Certificado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfe',
            field=models.IntegerField(default=1, help_text='Série atual para emissão de notas', verbose_name='Série NFe'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
