# Generated by Django 5.2.9 on 2026-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_empresa_ambiente_nfe_empresa_bairro_empresa_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ambiente_nfe',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='certificado_digital',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_municipio_ibge',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='csc',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='csc_id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inscricao_municipal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='numero_nfe_atual',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='regime_tributario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='senha_certificado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='serie_nfe',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='uf',
        ),
    ]
