# Generated by Django 5.0.14 on 2026-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_remove_empresa_ambiente_nfe_remove_empresa_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ambiente_nfe',
            field=models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', help_text='Ambiente de emissão (Homologação = Teste)', max_length=1, verbose_name='Ambiente NFe'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_digital',
            field=models.FileField(blank=True, help_text='Arquivo .pfx ou .p12', null=True, upload_to='empresas/certificados/', verbose_name='Certificado Digital (A1)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='IE da empresa (obrigatório para NFe)', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='IM da empresa (opcional, para NFSe)', max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_nfe_atual',
            field=models.PositiveIntegerField(default=0, help_text='Número da última nota fiscal emitida', verbose_name='Última NFe Emitida'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - Excesso de Sublimite'), ('3', 'Regime Normal')], default='1', help_text='Regime de tributação para cálculo de impostos', max_length=1, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='senha_certificado',
            field=models.CharField(blank=True, help_text='Senha para descriptografar o certificado', max_length=100, verbose_name='Senha do Certificado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfe',
            field=models.CharField(default='1', help_text='Série utilizada na emissão', max_length=3, verbose_name='Série NFe'),
        ),
    ]
