# Generated by Django 5.2.9 on 2025-12-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
    ]
