# Generated by Django 5.2.9 on 2025-12-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_pedido_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='lanches/')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanches', to='vendas.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='lanche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='vendas.produto'),
        ),
        migrations.DeleteModel(
            name='Lanche',
        ),
    ]
