# Generated by Django 5.2.9 on 2025-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_produto_alter_itempedido_lanche_delete_lanche'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
