# Generated by Django 5.2.9 on 2025-12-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '__first__'),
        ('vendas', '0004_produto_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='financeiro.costcenter'),
        ),
    ]
