# Generated by Django 5.2.9 on 2025-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_produto_categoria_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ean',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Kilograma'), ('LT', 'Litro')], default='UN', max_length=4),
        ),
    ]
