# Generated by Django 5.2.9 on 2025-12-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_backfill_sku_and_add_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='atributos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/')),
                ('alt', models.CharField(blank=True, max_length=160)),
                ('pos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='vendas.produto')),
            ],
            options={
                'ordering': ['pos', 'id'],
            },
        ),
    ]
