# Generated by Django 5.2.9 on 2025-12-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_produto_atributos_produto_cfop_produto_ncm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('BOOL', 'Booleano')], default='TEXT', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAtributoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.CharField(blank=True, max_length=160)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_bool', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='vendas.produtoatributo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_valores', to='vendas.produto')),
            ],
            options={
                'unique_together': {('produto', 'atributo')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('atributos', models.JSONField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/variacoes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='vendas.produto')),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='vendas_prod_sku_b7375b_idx')],
            },
        ),
    ]
