# Generated by Django 5.2.9 on 2026-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, help_text='Código do município no IBGE (obrigatório para NFe)', max_length=7, verbose_name='Código IBGE'),
        ),
    ]
