# Generated by Django 5.2.9 on 2026-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_endereco_codigo_municipio_ibge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='codigo_municipio_ibge',
        ),
    ]
