# Generated by Django 5.0.14 on 2026-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_endereco_codigo_municipio_ibge'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, help_text='Código do município no IBGE (7 dígitos) - Obrigatório para NFe', max_length=7, verbose_name='Código IBGE'),
        ),
    ]
