# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('VENDEDOR', 'Vendedor'), ('CAIXA', 'Operador de Caixa'), ('ESTOQUISTA', 'Estoquista'), ('FINANCEIRO', 'Financeiro')], db_index=True, default='VENDEDOR', help_text='Função do usuário no sistema', max_length=20, verbose_name='Cargo')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, verbose_name='Telefone')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Avatar do usuário', null=True, upload_to='usuarios/fotos/', verbose_name='Foto de Perfil')),
                ('receber_notificacoes_email', models.BooleanField(default=True, help_text='Enviar notificações do sistema por email', verbose_name='Receber Notificações por Email')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual o usuário pertence', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='tenant.empresa', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['empresa', 'username'],
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='authenticat_empresa_82af72_idx'), models.Index(fields=['cargo'], name='authenticat_cargo_7c81f4_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
