# Generated by Django 5.2.9 on 2026-01-15 20:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo do produto no momento da venda (snapshot)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Unitário'),
        ),
    ]
