# Generated by Django 5.0.14 on 2026-01-22 13:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_colaborador'),
        ('sales', '0002_itemvenda_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='Colaborador que receberá comissão (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_comissionadas', to='partners.colaborador', verbose_name='Colaborador/Garçom'),
        ),
        migrations.AddField(
            model_name='venda',
            name='comissao_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor calculado da comissão', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Comissão'),
        ),
    ]
