# Generated by Django 5.0.14 on 2026-01-22 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_colaborador'),
        ('sales', '0003_venda_colaborador_venda_comissao_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='atendente',
            field=models.ForeignKey(blank=True, help_text='Usuário atendente que receberá comissão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente/Garçom'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='colaborador',
            field=models.ForeignKey(blank=True, help_text='(Depreciado) Use o campo atendente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_comissionadas', to='partners.colaborador', verbose_name='Colaborador/Garçom (Legacy)'),
        ),
    ]
