# Generated by Django 5.0.14 on 2026-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_venda_atendente_alter_venda_colaborador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "PIX"),
                    ("CARTAO_DEBITO", "Cartão de Débito"),
                    ("CARTAO_CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência Bancária"),
                    ("CONTA_CLIENTE", "Conta Cliente (A Prazo)"),
                ],
                default="DINHEIRO",
                help_text="Forma de pagamento utilizada",
                max_length=20,
                verbose_name="Tipo de Pagamento",
            ),
        ),
    ]
