# Generated by Django 5.2.9 on 2025-12-29 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('documento', models.CharField(blank=True, max_length=32)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enderecos', models.ManyToManyField(blank=True, related_name='fornecedores', to='cadastro.address')),
            ],
        ),
    ]
