# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('codigo', models.CharField(db_index=True, help_text='Número do cartão/ficha (ex: A01, 0042)', max_length=50, verbose_name='Código')),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('EM_USO', 'Em Uso'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='LIVRE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Notas (ex: motivo do bloqueio)', verbose_name='Observações')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('venda_atual', models.OneToOneField(blank=True, help_text='Venda aberta vinculada a esta comanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comanda', to='sales.venda', verbose_name='Venda Atual')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='restaurant__empresa_984d09_idx'), models.Index(fields=['codigo'], name='restaurant__codigo_3640a1_idx')],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero', models.PositiveIntegerField(help_text='Número da mesa (ex: 10)', verbose_name='Número')),
                ('capacidade', models.PositiveIntegerField(default=4, help_text='Quantidade de pessoas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade')),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('SUJA', 'Suja')], db_index=True, default='LIVRE', help_text='Status atual da mesa', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre a mesa', verbose_name='Observações')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('venda_atual', models.OneToOneField(blank=True, help_text='Venda aberta vinculada a esta mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa', to='sales.venda', verbose_name='Venda Atual')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='restaurant__empresa_9ae93d_idx'), models.Index(fields=['numero'], name='restaurant__numero_5da0c3_idx')],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SetorImpressao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Nome do setor (ex: Cozinha, Bar, Copa)', max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs', max_length=120, verbose_name='Slug')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor de identificação (hex: #RRGGBB)', max_length=7, verbose_name='Cor')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Setor de Impressão',
                'verbose_name_plural': 'Setores de Impressão',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='restaurant__empresa_b91600_idx'), models.Index(fields=['slug'], name='restaurant__slug_8126ea_idx')],
                'unique_together': {('empresa', 'slug')},
            },
        ),
    ]
