# Generated by Django 5.2.9 on 2026-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='indicador_ie',
            field=models.CharField(choices=[('1', 'Contribuinte ICMS'), ('2', 'Contribuinte Isento'), ('9', 'Não Contribuinte')], default='9', help_text='Indicador da Inscrição Estadual para NFe', max_length=1, verbose_name='Indicador IE'),
        ),
    ]
