# Generated by Django 5.2.9 on 2026-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_cliente_indicador_ie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='indicador_ie',
        ),
    ]
