# Generated by Django 5.0.14 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_cliente_indicador_ie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(db_index=True, help_text='CPF ou CNPJ do fornecedor', max_length=20, verbose_name='CPF/CNPJ'),
        ),
    ]
