# Generated by Django 5.0.14 on 2026-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_fornecedor_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(blank=True, db_index=True, help_text='CPF ou CNPJ do fornecedor', max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
