# Generated by Django 5.0.14 on 2026-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_fornecedor_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='indicador_ie',
            field=models.CharField(choices=[('1', 'Contribuinte ICMS'), ('2', 'Contribuinte Isento'), ('9', 'Não Contribuinte')], default='9', help_text='Indicador da IE do Destinatário', max_length=1, verbose_name='Indicador IE'),
        ),
    ]
