# Generated by Django 5.0.14 on 2026-01-22 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_cliente_indicador_ie'),
        ('tenant', '0004_empresa_ambiente_nfe_empresa_certificado_digital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('cargo', models.CharField(choices=[('GERENTE', 'Gerente'), ('CAIXA', 'Operador de Caixa'), ('GARCOM', 'Garçom'), ('COZINHEIRO', 'Cozinheiro'), ('ENTREGADOR', 'Entregador'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de comissão sobre vendas', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% Comissão')),
                ('ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuário para login (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
