# Generated by Django 5.0.14 on 2026-01-26 19:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0007_colaborador"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="limite_credito",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Limite máximo para vendas a prazo (0 = sem limite)",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Limite de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="saldo_devedor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total que o cliente deve atualmente (atualizado pelo financeiro)",
                max_digits=15,
                verbose_name="Saldo Devedor",
            ),
        ),
    ]
