# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='setor_impressao',
            field=models.ForeignKey(blank=True, help_text='Setor onde o pedido deste produto será impresso (ex: Cozinha, Bar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='restaurant.setorimpressao', verbose_name='Setor de Impressão'),
        ),
        migrations.AddField(
            model_name='grupocomplemento',
            name='produtos_vinculados',
            field=models.ManyToManyField(help_text='Produtos que possuem este grupo de complementos', related_name='grupos_complementos', to='catalog.produto', verbose_name='Produtos'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='produto_referencia',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, baixa estoque deste produto ao adicionar (ex: Bacon, Ovo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementos_vinculados', to='catalog.produto', verbose_name='Produto Referência'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['empresa', 'parent'], name='catalog_cat_empresa_50add1_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_331422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'categoria'], name='catalog_pro_empresa_ae2ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'tipo'], name='catalog_pro_empresa_de03de_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_72033d_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo_barras'], name='catalog_pro_codigo__765efb_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['destaque', 'is_active'], name='catalog_pro_destaqu_67e5ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('empresa', 'codigo_barras'), ('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='grupocomplemento',
            index=models.Index(fields=['empresa', 'is_active'], name='catalog_gru_empresa_417259_idx'),
        ),
        migrations.AddIndex(
            model_name='complemento',
            index=models.Index(fields=['empresa', 'grupo'], name='catalog_com_empresa_cc98b4_idx'),
        ),
        migrations.AddIndex(
            model_name='complemento',
            index=models.Index(fields=['produto_referencia'], name='catalog_com_produto_cfe8cb_idx'),
        ),
    ]
