# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('object_id', models.UUIDField(help_text='UUID da entidade associada', verbose_name='ID do Objeto')),
                ('tipo', models.CharField(choices=[('COBRANCA', 'Cobrança'), ('ENTREGA', 'Entrega'), ('FISICO', 'Físico'), ('COMERCIAL', 'Comercial'), ('RESIDENCIAL', 'Residencial')], db_index=True, default='COMERCIAL', help_text='Finalidade do endereço', max_length=20, verbose_name='Tipo de Endereço')),
                ('cep', models.CharField(help_text='Código de Endereçamento Postal (com ou sem hífen)', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000 ou 00000000', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP')),
                ('logradouro', models.CharField(help_text='Rua, avenida, travessa, etc.', max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(help_text='Número do endereço (use "S/N" para sem número)', max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Apartamento, sala, bloco, etc. (opcional)', max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(help_text='Bairro ou distrito', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Município', max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Unidade Federativa (Estado)', max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada geográfica (opcional)', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada geográfica (opcional)', max_digits=10, null=True, verbose_name='Longitude')),
                ('referencia', models.TextField(blank=True, help_text='Informações adicionais para localização (opcional)', verbose_name='Ponto de Referência')),
                ('content_type', models.ForeignKey(help_text='Tipo da entidade associada (Cliente, Fornecedor, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='locations_e_content_22b15a_idx'), models.Index(fields=['empresa', 'tipo'], name='locations_e_empresa_11daff_idx'), models.Index(fields=['cep'], name='locations_e_cep_25f26a_idx'), models.Index(fields=['cidade', 'uf'], name='locations_e_cidade_0c6191_idx')],
            },
        ),
    ]
