# Generated by Django 5.2.9 on 2025-12-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
