# Generated by Django 5.2.9 on 2025-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_purchaseorder_pago_em_purchaseorder_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Recebido', 'Recebido'), ('Cancelado', 'Cancelado'), ('Quitado', 'Quitado')], default='Pendente', max_length=20),
        ),
    ]
