# Generated by Django 5.0.14 on 2026-01-22 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('sales', '0002_itemvenda_custo_unitario'),
        ('tenant', '0004_empresa_ambiente_nfe_empresa_certificado_digital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Identificação do caixa (ex: Caixa 01)', max_length=50, verbose_name='Nome do Caixa')),
                ('serial', models.CharField(blank=True, help_text='Identificador único ou serial do equipamento (opcional)', max_length=50, verbose_name='Serial/ID')),
                ('ativo', models.BooleanField(default=True, help_text='Se o caixa está disponível para uso', verbose_name='Ativo')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Inicial (Fundo de Troco)')),
                ('saldo_final_informado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor contado fisicamente pelo operador no fechamento', max_digits=15, null=True, verbose_name='Saldo Final Informado')),
                ('saldo_final_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor esperado pelo sistema (Inicial + Vendas - Sangrias + Suprimentos)', max_digits=15, null=True, verbose_name='Saldo Final Calculado')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='financial.caixa', verbose_name='Caixa')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('SUPRIMENTO', 'Suprimento (Entrada)'), ('SANGRIA', 'Sangria (Saída)'), ('VENDA', 'Venda (Recebimento)')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição/Motivo')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('venda_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='sales.venda', verbose_name='Venda de Origem')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financial.sessaocaixa', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='sessaocaixa',
            index=models.Index(fields=['empresa', 'status'], name='financial_s_empresa_ec65cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocaixa',
            index=models.Index(fields=['empresa', 'operador'], name='financial_s_empresa_37ed7d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocaixa',
            index=models.Index(fields=['empresa', 'data_abertura'], name='financial_s_empresa_910bc3_idx'),
        ),
    ]
