# Generated by Django 5.0.14 on 2026-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0002_caixa_sessaocaixa_movimentocaixa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contapagar",
            name="tipo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "PIX"),
                    ("CARTAO_DEBITO", "Cartão de Débito"),
                    ("CARTAO_CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência Bancária"),
                    ("CHEQUE", "Cheque"),
                    ("CONTA_CLIENTE", "Conta Cliente (A Prazo)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="contareceber",
            name="tipo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "PIX"),
                    ("CARTAO_DEBITO", "Cartão de Débito"),
                    ("CARTAO_CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência Bancária"),
                    ("CHEQUE", "Cheque"),
                    ("CONTA_CLIENTE", "Conta Cliente (A Prazo)"),
                ],
                help_text="Forma de pagamento utilizada",
                max_length=20,
                null=True,
                verbose_name="Tipo de Pagamento",
            ),
        ),
    ]
