# Generated by Django 5.2.9 on 2026-01-14 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False, help_text='Número sequencial da venda (gerado automaticamente)', verbose_name='Número')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', verbose_name='Slug')),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('PENDENTE', 'Pendente'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ORCAMENTO', help_text='Status atual da venda', max_length=20, verbose_name='Status')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma de todos os subtotais dos itens', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Bruto')),
                ('total_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma de todos os descontos aplicados', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Desconto')),
                ('total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total bruto - total desconto (valor final)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Líquido')),
                ('tipo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária')], default='DINHEIRO', help_text='Forma de pagamento utilizada', max_length=20, verbose_name='Tipo de Pagamento')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da venda', verbose_name='Data de Emissão')),
                ('data_finalizacao', models.DateTimeField(blank=True, help_text='Data e hora em que a venda foi finalizada', null=True, verbose_name='Data de Finalização')),
                ('data_cancelamento', models.DateTimeField(blank=True, help_text='Data e hora em que a venda foi cancelada', null=True, verbose_name='Data de Cancelamento')),
                ('observacoes', models.TextField(blank=True, help_text='Notas ou comentários sobre a venda (opcional)', verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente da venda (nullable para venda balcão/sem cadastro)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='partners.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('vendedor', models.ForeignKey(help_text='Usuário responsável pela venda', on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade vendida', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço do produto no momento da venda (snapshot)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto aplicado neste item', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(quantidade × preço) + complementos - desconto', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas deste item (ex: sem cebola, ponto da carne)', verbose_name='Observações')),
                ('status_producao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue')], db_index=True, default='PENDENTE', help_text='Status atual na cozinha/bar', max_length=20, verbose_name='Status de Produção')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(help_text='Produto vendido', on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='catalog.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(help_text='Venda à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemVendaComplemento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantidade deste complemento', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço adicional do complemento (snapshot)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='quantidade × preço unitário', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('complemento', models.ForeignKey(help_text='Complemento escolhido pelo cliente', on_delete=django.db.models.deletion.PROTECT, related_name='itens_vendidos', to='catalog.complemento', verbose_name='Complemento')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('item_pai', models.ForeignKey(help_text='Item de venda ao qual este complemento pertence', on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='sales.itemvenda', verbose_name='Item Pai')),
            ],
            options={
                'verbose_name': 'Complemento do Item',
                'verbose_name_plural': 'Complementos dos Itens',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['item_pai', 'complemento'], name='sales_itemv_item_pa_a89b2c_idx'), models.Index(fields=['empresa', 'complemento'], name='sales_itemv_empresa_b976b1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'status'], name='sales_venda_empresa_459521_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'numero'], name='sales_venda_empresa_59808e_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['vendedor', 'data_emissao'], name='sales_venda_vendedo_5adf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente', 'data_emissao'], name='sales_venda_cliente_d2b76d_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['slug'], name='sales_venda_slug_e29cfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('empresa', 'numero'), ('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['venda', 'produto'], name='sales_itemv_venda_i_774be2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['empresa', 'produto'], name='sales_itemv_empresa_ea4c2c_idx'),
        ),
    ]
