# Generated by Django 5.2.9 on 2026-01-15 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_add_ficha_tecnica'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('cnpj_fornecedor', models.CharField(help_text='CNPJ do fornecedor (apenas números)', max_length=14, verbose_name='CNPJ Fornecedor')),
                ('nome_fornecedor', models.CharField(help_text='Razão social ou nome fantasia', max_length=200, verbose_name='Nome do Fornecedor')),
                ('codigo_no_fornecedor', models.CharField(help_text='Código/SKU/EAN do produto no fornecedor', max_length=50, verbose_name='Código no Fornecedor')),
                ('fator_conversao', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Quantas unidades do produto equivalem a 1 unidade do fornecedor (ex: 12 para caixas)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Fator de Conversão')),
                ('ultimo_preco', models.DecimalField(blank=True, decimal_places=2, help_text='Último preço de compra (por unidade do fornecedor)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Último Preço')),
                ('data_ultima_compra', models.DateTimeField(auto_now=True, help_text='Atualizado automaticamente a cada importação', verbose_name='Data Última Compra')),
                ('observacao', models.TextField(blank=True, help_text='Notas sobre este vínculo', verbose_name='Observação')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_fornecedor', to='catalog.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Vínculo Produto-Fornecedor',
                'verbose_name_plural': 'Vínculos Produto-Fornecedor',
                'db_table': 'nfe_produto_fornecedor',
                'ordering': ['-data_ultima_compra'],
                'indexes': [models.Index(fields=['cnpj_fornecedor'], name='nfe_produto_cnpj_fo_5e6c2f_idx'), models.Index(fields=['codigo_no_fornecedor'], name='nfe_produto_codigo__5384a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cnpj_fornecedor', 'codigo_no_fornecedor'), name='unique_vinculo_produto_fornecedor')],
            },
        ),
    ]
