# Generated by Django 5.2.9 on 2026-01-16 13:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_produto_cest_produto_cfop_padrao_produto_ncm_and_more'),
        ('nfe', '0001_initial'),
        ('partners', '0002_cliente_indicador_ie'),
        ('sales', '0002_itemvenda_custo_unitario'),
        ('tenant', '0002_empresa_ambiente_nfe_empresa_bairro_empresa_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('serie', models.IntegerField(verbose_name='Série')),
                ('modelo', models.CharField(default='55', max_length=2, verbose_name='Modelo')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('tipo_emissao', models.CharField(choices=[('1', 'Normal'), ('2', 'Contingência FS-IA'), ('3', 'Contingência SCAN'), ('4', 'Contingência DPEC'), ('5', 'Contingência FS-DA'), ('6', 'Contingência SVC-AN'), ('7', 'Contingência SVC-RS'), ('9', 'Contingência Offline (NFCe)')], default='1', max_length=1, verbose_name='Tipo de Emissão')),
                ('status', models.CharField(choices=[('DIGITACAO', 'Em Digitação'), ('VALIDADA', 'Validada'), ('ASSINADA', 'Assinada'), ('TRANSMITIDA', 'Transmitida'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada')], default='DIGITACAO', max_length=20, verbose_name='Status')),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=50, verbose_name='Protocolo Autorização')),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data Autorização')),
                ('motivo_status', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Erro SEFAZ')),
                ('xml_envio', models.TextField(blank=True, verbose_name='XML Envio')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML Retorno')),
                ('xml_processado', models.TextField(blank=True, verbose_name='XML Processado (ProcNFe)')),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total_nota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.cliente', verbose_name='Destinatário')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='sales.venda', verbose_name='Venda de Origem')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'modelo', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código Produto')),
                ('descricao_produto', models.CharField(max_length=120, verbose_name='Descrição')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=7, verbose_name='CEST')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('unidade', models.CharField(max_length=6, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('icms_origem', models.CharField(default='0', max_length=1)),
                ('icms_cst', models.CharField(default='102', max_length=3)),
                ('icms_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('icms_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.produto', verbose_name='Produto')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nfe.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens da Nota Fiscal',
            },
        ),
    ]
