# Generated by Django 5.2.9 on 2026-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0002_notafiscal_itemnotafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='ambiente',
            field=models.CharField(default='2', max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='natureza_operacao',
            field=models.CharField(default='VENDA', max_length=60, verbose_name='Natureza da Operação'),
        ),
    ]
