# Generated by Django 5.2.9 on 2026-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0003_notafiscal_ambiente_notafiscal_natureza_operacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='venda',
        ),
        migrations.DeleteModel(
            name='ItemNotaFiscal',
        ),
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
    ]
