# Generated by Django 5.0.14 on 2026-01-20 21:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_produto_cest_produto_cfop_padrao_produto_ncm_and_more'),
        ('nfe', '0004_alter_notafiscal_unique_together_and_more'),
        ('partners', '0006_cliente_indicador_ie'),
        ('sales', '0002_itemvenda_custo_unitario'),
        ('tenant', '0004_empresa_ambiente_nfe_empresa_certificado_digital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('serie', models.PositiveIntegerField(verbose_name='Série')),
                ('modelo', models.CharField(default='55', help_text='55=NFe, 65=NFCe', max_length=2, verbose_name='Modelo')),
                ('tipo_emissao', models.CharField(choices=[('1', 'Normal'), ('2', 'Contingência FS-IA'), ('3', 'Contingência SCAN'), ('4', 'Contingência EPEC'), ('5', 'Contingência FS-DA'), ('6', 'Contingência SVC-AN'), ('7', 'Contingência SVC-RS'), ('9', 'Contingência Offline')], default='1', max_length=1, verbose_name='Tipo de Emissão')),
                ('status', models.CharField(choices=[('DIGITACAO', 'Em Digitação'), ('VALIDADA', 'Validada'), ('ASSINADA', 'Assinada'), ('TRANSMITIDA', 'Transmitida'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada')], default='DIGITACAO', max_length=20, verbose_name='Status')),
                ('natureza_operacao', models.CharField(default='VENDA', max_length=60, verbose_name='Natureza da Operação')),
                ('ambiente', models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', max_length=1, verbose_name='Ambiente')),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, verbose_name='Chave de Acesso')),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=15, verbose_name='Protocolo')),
                ('xml_envio', models.TextField(blank=True, verbose_name='XML Envio')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML Retorno')),
                ('xml_processado', models.TextField(blank=True, verbose_name='XML Processado (ProcNFe)')),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Produtos')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Frete')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Seguro')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Desconto')),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Outras Despesas')),
                ('valor_total_nota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total da Nota')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.cliente', verbose_name='Destinatário')),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='sales.venda', verbose_name='Venda de Origem')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUID v4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero_item', models.PositiveIntegerField(verbose_name='Nº Item')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código')),
                ('descricao_produto', models.CharField(max_length=120, verbose_name='Descrição')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=7, verbose_name='CEST')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('unidade_comercial', models.CharField(max_length=6, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Frete')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Seguro')),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Outras Despesas')),
                ('origem', models.CharField(default='0', max_length=1, verbose_name='Origem')),
                ('csosn', models.CharField(blank=True, max_length=4, verbose_name='CSOSN')),
                ('cst_pis', models.CharField(blank=True, max_length=2, verbose_name='CST PIS')),
                ('cst_cofins', models.CharField(blank=True, max_length=2, verbose_name='CST COFINS')),
                ('cst_ipi', models.CharField(blank=True, max_length=2, verbose_name='CST IPI')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('base_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('empresa', models.ForeignKey(help_text='Empresa à qual este registro pertence (tenant)', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenant.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.produto', verbose_name='Produto')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nfe.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens da Nota Fiscal',
                'ordering': ['numero_item'],
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['chave_acesso'], name='nfe_notafis_chave_a_3980b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['status'], name='nfe_notafis_status_899e49_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['data_emissao'], name='nfe_notafis_data_em_5cd794_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'modelo', 'serie', 'numero'), name='unique_nfe_numero'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscal',
            constraint=models.UniqueConstraint(fields=('nota', 'numero_item'), name='unique_item_nfe'),
        ),
    ]
