# Generated by Django 5.0.14 on 2026-01-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0005_notafiscal_itemnotafiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='finalidade',
            field=models.CharField(choices=[('1', 'NFe Normal'), ('2', 'NFe Complementar'), ('3', 'NFe de Ajuste'), ('4', 'Devolução de Mercadoria')], default='1', max_length=1, verbose_name='Finalidade'),
        ),
    ]
